platform :osx, '10.13'

target 'Example' do
  use_frameworks!

  pod 'Subprocess', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
    pod 'Subprocess/Mocks', :path => '../'
  end

end
